In [1]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical

In [2]:
mnist = pd.read_csv(r'MNIST_Train.csv')
mnist = np.array(mnist)
mnist_x = mnist[:,1:]
mnist_x.shape

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

(42000, 784)

In [3]:
mnist_y = mnist[:,0]

In [4]:
mnist_x = mnist_x.reshape(-1, 28,28,1)
mnist_x.shape
mnist_x = tf.keras.utils.normalize(mnist_x)
mnist_y

<IPython.core.display.Javascript object>

array([1, 0, 1, ..., 7, 6, 9], dtype=int64)

In [5]:
mnist_y = to_categorical(mnist_y)
mnist_y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [6]:
mnist_x.shape

(42000, 28, 28, 1)

In [7]:
mnist_y[100]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

# Model Buliding

In [8]:
model = Sequential()
model.add(Conv2D(filters = 16, kernel_size = (5,5), activation = 'relu', padding="same", input_shape=(28, 28, 1)))
model.add(MaxPool2D(pool_size = (2,2)))
model.add(Conv2D(filters = 32, kernel_size = (5,5), activation = 'relu'))
model.add(MaxPool2D(pool_size = (2,2)))
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.4))
model.add(Dense(10, activation = 'softmax'))

In [9]:
adam = tf.keras.optimizers.Adam(lr = 1) # its not Mandatory Default is 0.01
model.compile(optimizer= 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

<IPython.core.display.Javascript object>

C:\Users\shubh\anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [10]:
model.fit(mnist_x, mnist_y, epochs = 2, validation_split= 0.2, batch_size = 32)

Epoch 1/2
1050/1050 [==============================] - 9s 8ms/step - loss: 0.2709 - accuracy: 0.9150 - val_loss: 0.1025 - val_accuracy: 0.9688
Epoch 2/2
1050/1050 [==============================] - 8s 8ms/step - loss: 0.0992 - accuracy: 0.9704 - val_loss: 0.0604 - val_accuracy: 0.9819


In [11]:
from sklearn.metrics import confusion_matrix
predict_x = model.predict(mnist_x)
classes_x = np.argmax(predict_x, axis =1)
classes_y = np.argmax(mnist_y, axis =1)
con_mat = confusion_matrix(classes_x,classes_y)
print(con_mat)
acc = con_mat.diagonal().sum() *100/con_mat.sum()
acc

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[4123    0   10    2    4    5   16    1   12   13]
 [   1 4656    9    2    6    0    6    9   37    5]
 [   0   10 4113   11    1    0    0   21    8    0]
 [   1    1   18 4258    0   32    0    3    1    8]
 [   1    6    2    0 4013    1    4    7    4   16]
 [   0    0    0    5    0 3709    6    0    4    5]
 [   4    0    0    0    5   17 4100    0    3    0]
 [   0    6   15   12    2    3    0 4336    2   23]
 [   1    3    8   40    2   16    5    5 3968   10]
 [   1    2    2   21   39   12    0   19   24 4108]]


98.53333333333333

# Sampling Data and then Building Model

In [12]:
from sklearn.model_selection import train_test_split
mnist_x_train, mnist_x_test, mnist_y_train, mnist_y_test = train_test_split(mnist_x, mnist_y, test_size = .2)

In [13]:
mnist_x_train = tf.keras.utils.normalize(mnist_x_train)
mnist_x_test = tf.keras.utils.normalize(mnist_x_test)   # Normalize is not mandatory but its been observed it gives good results.

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [14]:
model = Sequential()
model.add(Conv2D(filters = 16, kernel_size = (5,5), activation = 'relu', padding="same", input_shape=(28, 28, 1)))
model.add(MaxPool2D(pool_size = (2,2)))
model.add(Conv2D(filters = 32, kernel_size = (5,5), activation = 'relu'))
model.add(MaxPool2D(pool_size = (2,2)))
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.4))
model.add(Dense(10, activation = 'softmax'))

In [15]:
adam = tf.keras.optimizers.Adam(lr = 3) # its not Mandatory Default is 0.01
model.compile(optimizer= adam, loss = 'categorical_crossentropy', metrics = ['accuracy'])


<IPython.core.display.Javascript object>

C:\Users\shubh\anaconda3\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(


In [16]:
model1 = model.fit(mnist_x_train, mnist_y_train, epochs=10, validation_split=.2, batch_size = 32)

Epoch 1/10
840/840 [==============================] - 7s 8ms/step - loss: 860456.0000 - accuracy: 0.1005 - val_loss: 2.7113 - val_accuracy: 0.0955
Epoch 2/10
840/840 [==============================] - 6s 8ms/step - loss: 2.5838 - accuracy: 0.1009 - val_loss: 2.8089 - val_accuracy: 0.1009
Epoch 3/10
840/840 [==============================] - 7s 8ms/step - loss: 2.6098 - accuracy: 0.1015 - val_loss: 2.6756 - val_accuracy: 0.1016
Epoch 4/10
840/840 [==============================] - 6s 8ms/step - loss: 2.5746 - accuracy: 0.0997 - val_loss: 2.5684 - val_accuracy: 0.0955
Epoch 5/10
840/840 [==============================] - 7s 8ms/step - loss: 2.5911 - accuracy: 0.1015 - val_loss: 2.3612 - val_accuracy: 0.0964
Epoch 6/10
840/840 [==============================] - 7s 8ms/step - loss: 2.5999 - accuracy: 0.1022 - val_loss: 2.5927 - val_accuracy: 0.0955
Epoch 7/10
840/840 [==============================] - 6s 8ms/step - loss: 2.5578 - accuracy: 0.0983 - val_loss: 2.6206 - val_accuracy: 0.0955
E

In [17]:
from sklearn.metrics import confusion_matrix
predict_x_test = model.predict(mnist_x_test)
classes_x = np.argmax(predict_x_test, axis =1)
classes_y = np.argmax(mnist_y_test, axis =1)
con_mat = confusion_matrix(classes_x,classes_y)
print(con_mat)
acc = con_mat.diagonal().sum() *100/con_mat.sum()
acc

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [883 927 786 903 821 786 785 880 810 819]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]


10.476190476190476